version: '3.8'
services:
  db:
    user: root
    container_name: db
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db

  pgadmin:
    user: root
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_USER: 'postgres'
      PGADMIN_DEFAULT_EMAIL: 'postgres@postgres.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - '8001:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db

  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - db

networks:
  db:
    driver: bridge
